#!/bin/sh

### BEGIN INIT INFO
# Provides:          rulispdaemon
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start rulisp server at boot time
### END INIT INFO

start () {
	echo -n "Starting rulisp server... "

    export LC_ALL="ru_RU.UTF-8"

    start-stop-daemon --start \
        --pidfile /var/rulisp/rulisp.pid \
        --startas /usr/bin/screen \
        --chuid rulisp \
        -- \
        -d -m -c /dev/null -S rulisp /usr/bin/sbcl --dynamic-space-size 400 --no-userinit --load /usr/share/rulisp/rulisp-start.lisp
#    sbcl --noinform --dynamic-space-size 400 --no-userinit --no-systeminit --load /usr/share/rulisp/rulisp-daemon.lisp start
		       
	[ $? -eq 0 ] && echo "done." || echo "failed!"
}

stop () {
	echo -n "Stopping rulisp server... "
    start-stop-daemon --stop --pidfile /var/rulisp/rulisp.pid
#    sbcl --noinform --dynamic-space-size 400 --no-userinit --no-systeminit --load /usr/share/rulisp/rulisp-daemon.lisp kill
    
	[ $? -eq 0 ] && echo "done." || echo "failed!"
}

help () {
	echo "Usage: $0 <start|stop|restart>"
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop && start ;;
    *) help ;;
esac
